# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hello.proto for package 'protos'

require 'grpc'
require 'hello_pb'

module Protos
  module Ping
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'protos.Ping'

      rpc :SayHello, PingMsg, PingMsg
    end

    Stub = Service.rpc_stub_class
  end
end
