# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protos.PingMsg" do
    optional :greeting, :string, 1
  end
end

module Protos
  PingMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.PingMsg").msgclass
end
