// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/hello.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Msg struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver             string   `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_a63830eae10ef472, []int{0}
}
func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (dst *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(dst, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Msg) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Msg) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*Msg)(nil), "protos.Msg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatClient interface {
	Chewing(ctx context.Context, opts ...grpc.CallOption) (Chat_ChewingClient, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) Chewing(ctx context.Context, opts ...grpc.CallOption) (Chat_ChewingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Chat_serviceDesc.Streams[0], "/protos.Chat/Chewing", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatChewingClient{stream}
	return x, nil
}

type Chat_ChewingClient interface {
	Send(*Msg) error
	Recv() (*Msg, error)
	grpc.ClientStream
}

type chatChewingClient struct {
	grpc.ClientStream
}

func (x *chatChewingClient) Send(m *Msg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatChewingClient) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServer is the server API for Chat service.
type ChatServer interface {
	Chewing(Chat_ChewingServer) error
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_Chewing_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).Chewing(&chatChewingServer{stream})
}

type Chat_ChewingServer interface {
	Send(*Msg) error
	Recv() (*Msg, error)
	grpc.ServerStream
}

type chatChewingServer struct {
	grpc.ServerStream
}

func (x *chatChewingServer) Send(m *Msg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatChewingServer) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chewing",
			Handler:       _Chat_Chewing_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/hello.proto",
}

func init() { proto.RegisterFile("protos/hello.proto", fileDescriptor_hello_a63830eae10ef472) }

var fileDescriptor_hello_a63830eae10ef472 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0xd7, 0x03, 0x73, 0x84, 0xd8, 0x20, 0x62, 0x4a,
	0xbe, 0x5c, 0xcc, 0xbe, 0xc5, 0xe9, 0x42, 0x62, 0x5c, 0x6c, 0xc5, 0xa9, 0x79, 0x29, 0xa9, 0x45,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x9e, 0x90, 0x14, 0x17, 0x47, 0x51, 0x6a, 0x72,
	0x6a, 0x66, 0x59, 0x6a, 0x91, 0x04, 0x13, 0x58, 0x06, 0xce, 0x17, 0x12, 0xe2, 0x62, 0x29, 0x49,
	0xad, 0x28, 0x91, 0x60, 0x06, 0x8b, 0x83, 0xd9, 0x46, 0x86, 0x5c, 0x2c, 0xce, 0x19, 0x89, 0x25,
	0x42, 0x9a, 0x5c, 0xec, 0xce, 0x19, 0xa9, 0xe5, 0x99, 0x79, 0xe9, 0x42, 0xdc, 0x10, 0x1b, 0x8b,
	0xf5, 0x7c, 0x8b, 0xd3, 0xa5, 0x90, 0x39, 0x4a, 0x0c, 0x1a, 0x8c, 0x06, 0x8c, 0x49, 0x10, 0x97,
	0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xa4, 0xbc, 0x45, 0xa6, 0x00, 0x00, 0x00,
}
